# Generated by Django 6.0.4 on 2026-04-25 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='题目名称')),
                ('subject', models.CharField(blank=True, default='', max_length=20, verbose_name='学科')),
                ('knowledge_point', models.CharField(blank=True, default='', max_length=100, verbose_name='知识点')),
                ('difficulty', models.CharField(blank=True, choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='', max_length=10, verbose_name='难度')),
                ('error_type', models.CharField(blank=True, choices=[('concept', '概念模糊'), ('calculation', '计算失误'), ('reading', '审题偏差'), ('method', '方法错误'), ('blind_spot', '知识盲区')], default='', max_length=20, verbose_name='错误类型')),
                ('question_text', models.TextField(blank=True, default='', verbose_name='题目内容')),
                ('answer_text', models.TextField(blank=True, default='', verbose_name='正确答案')),
                ('original_image', models.ImageField(upload_to='questions/', verbose_name='原始图片')),
                ('ocr_raw_text', models.TextField(blank=True, default='', verbose_name='OCR原始文本')),
                ('ai_analysis_json', models.TextField(blank=True, default='', verbose_name='AI分析JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '错题',
                'verbose_name_plural': '错题',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField(blank=True, default='', verbose_name='学生回答')),
                ('is_correct', models.BooleanField(null=True, verbose_name='是否正确')),
                ('ai_feedback', models.TextField(blank=True, default='', verbose_name='AI批改反馈')),
                ('ai_score', models.CharField(blank=True, default='', max_length=20, verbose_name='AI评分')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='复习时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='errorbook.question', verbose_name='错题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '复习记录',
                'verbose_name_plural': '复习记录',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
