# Generated by Django 6.0.4 on 2026-04-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errorbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_mastered',
            field=models.BooleanField(default=False, verbose_name='是否已掌握'),
        ),
        migrations.AddField(
            model_name='question',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后复习时间'),
        ),
        migrations.AddField(
            model_name='question',
            name='next_review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次复习日期'),
        ),
        migrations.AddField(
            model_name='question',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='复习次数'),
        ),
    ]
